//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string PlayerName { get; set; }
        public Nullable<int> JerseyNumber { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> ClubRegNum { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
